spring:
  application:
    name: product-service # 서비스 이름 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always



  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 10000
      lettuce:
        pool:
          max-active: 200
          max-idle: 100
          min-idle: 20
          max-wait: 5000

  kafka:
    listener:
      type: batch
      batch-size: 50
      concurrency: 5
    consumer:
      auto-offset-reset: earliest
      group-id: product-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.sparta.product.dto.StockUpdateRequestDto
        session.timeout.ms: 60000
        heartbeat.interval.ms: 10000
        auto.offset.reset: earliest
      max-poll-records: 100
      fetch-min-size: 1048576
      fetch-max-wait-ms: 1000
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 10
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds : 600 # 5초마다 갱신
    disable-delta: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

    instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30
      prefer-ip-address: true
      instance-id: product-service:${random.value}
      non-secure-port-enabled: true
      metadata-map:
        instanceId: product-service:${random.value}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

server:
  port: 8082

  task:
    execution:
      pool:
        core-size: 20
        max-size: 50
        queue-capacity: 100
      shutdown:
        await-termination: true
        await-termination-period: 30s

resilience4j:
  retry:
    instances:
      redis-lock-retry:
        max-attempts: 5    #  최대 재시도 횟수
        wait-duration: 100ms #  재시도 간격
        enable-exponential-backoff: true  # 점진적으로 재시도 간격 증가
        exponential-backoff-multiplier: 1.5 #  점진적 증가 적용
        retry-exceptions:
          - java.lang.IllegalStateException

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    retries:
      enabled: true
    resilience4j:
      enabled: true