spring:
  datasource:
    # ??? ?? DB
    user:
      url: jdbc:mysql://haengyeo_mysql_user:3306/user_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
    # ?? ?? DB
    product:
      url: jdbc:mysql://haengyeo_mysql_product:3306/product_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
    # ?? ?? DB
    order:
      url: jdbc:mysql://haengyeo_mysql_order:3306/order_db
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update  # ?? ? create ? update? ???? ?? ???? ??
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8090

logging:
  level:
    com.sparta.hanghae_restock: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
