spring:
  datasource:
    url: jdbc:mysql://haengye_project:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create  # MySQL 연결 설정
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.naver.com
    port: 465
    username: ${EMAIL_USERNAME}  # 환경변수로 이메일 아이디 참조
    password: ${EMAIL_PASSWORD}  # 환경변수로 이메일 비밀번호 참조
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 10000
      lettuce:
        pool:
          max-active: 10             # 최대 커넥션 수
          max-idle: 5                # 최대 아이들 커넥션 수
          min-idle: 1                # 최소 아이들 커넥션 수
          max-wait: 10000            # 최대 대기 시간 (ms)

  jwt:
    secret: ${JWT_SECRET}  # JWT 비밀키 환경변수로 설정
    expiration: 3600000   # JWT 만료시간 (1시간)

server:
  port: 8090

logging:
  level:
    com.sparta.hanghae_restock: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
