spring:
  datasource:
    url: jdbc:mysql://localhost:3310/user_db
    username: user
    password: b12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create  # MySQL 연결 설정
    open-in-view: false
  sql:
    init:
      mode: always
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.naver.com
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true # TLS 활성화
      mail.smtp.ssl.enable: true # SSL 활성화
      mail.smtp.ssl.trust: smtp.naver.com # SSL 인증 설정
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 10000

# JWT 관련 설정 (사용할 경우 주석 해제)
  jwt:
   secret: ${JWT_SECRET}
   expiration: 1800000

server:
  port: 8090

logging:
  level:
    com.sparta.hanghae_project: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    com.sparta.haengye_project: DEBUG


