spring:
  application:
    name: order-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      mode: always



  data:
    redis:
      host: ${REDIS_HOST}  # Docker Compose 환경에서 Redis 컨테이너 이름
      port: ${REDIS_PORT}
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 10000

  feign:
    client:
      config:
        default:
          connect-timeout: 5000 # 연결 타임아웃 (밀리초)
          read-timeout: 5000    # 읽기 타임아웃 (밀리초)
          logger-level: FULL    # Feign 통신 로그 출력 수준 (FULL로 하면 요청/응답 모두 확인 가능)


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 600 # 5??? ??
    disable-delta: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
#      defaultZone: http://eureka-server:8761/eureka

  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    instance-id: order-service:${random.value}
    non-secure-port-enabled: true
    metadata-map:
      instanceId: order-service:${random.value}

  jwt:
    secret: ${JWT_SECRET}
    expiration: 3600000

server:
  port: 8084